menu:
  Home: /
  Archives: /archives


livere: true

# youyan:
#   on: true
#   id: acgknowledge
  # 是否开启友言评论，http://www.uyan.cc/index.php
  # id 中填写你的友言用户数字ID，注册后进入后台管理即可查看
  # 友言服务在 Web 环境下运行，普通本地环境无法查看，请部署后在线上测试。